services:
    app.importer:
        class: App\Finance\Transaction\Import\RabobankCsvImporter

    app.guesser:
        class: App\Finance\Transaction\Import\WalletGuesser

    app.form.book_transaction:
        class: App\Bundle\Form\BookTransactionForm
        arguments: ['@app.repository.wallet']
        tags:
            - { name: form.type }

    app.negotiation_listener:
        class: App\Bundle\EventListener\NegotiationListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: configureContentType }

    app.command_bus_middleware.validator:
        class: App\Bundle\CommandBus\ValidatorMiddleware
        arguments: ['@validator']
        tags:
            - { name: command_bus_middleware }

    app.validator.unique:
        class: App\Bundle\Validator\UniqueValidator
        arguments: ['@doctrine']
        tags:
            - { name: validator.constraint_validator, alias: app.validator.unique }
